name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Get Version
              run: |
                  version=$(cat ./README.md | grep -o "v.*")
                  echo "version=$version" >> $GITHUB_ENV
            - name: Check Version
              run: |
                  echo ${{ env.version }}
