name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout To Self Repo
              uses: actions/checkout@v4

            - name: Get Version
              run: |
                  version=$(cat ./README.md | grep -oP 'v\d+\.\d+\.\d+')
                  echo "version=$version" >> $GITHUB_ENV

            - name: Checkout To V8 Repo
              uses: actions/checkout@v4
              with:
                  repository: denoland/rusty_v8
                  ref: ${{ env.version }}
                  fetch-depth: 10
                  submodules: recursive

            - name: Install Rust
              uses: dsherret/rust-toolchain-file@v1

            - name: Install Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11.x
                  architecture: x64
