name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  repository: denoland/rusty_v8
                  ref: main
