name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Get Version
              run: |
                  version=$(cat ./README.md | grep -oP 'v\d+\.\d+\.\d+')
                  echo "version=$version" >> $GITHUB_ENV
            - name: Checkout Source Code
              if: ${{ env.version }}
              run: |
                  git clone --recursive https://github.com/denoland/rusty_v8
                  cd rusty_v8
                  git checkout ${{ env.version }}
                  git submodule update
