name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-22.04

        env:
            # V8_FROM_SOURCE: 1
            CARGO_VARIANT_FLAG: --release
            TARGET: x86_64-unknown-linux-gnu

        steps:
            - name: Checkout To Self Repo
              uses: actions/checkout@v4

            - name: Get Version
              id: get_version
              run: |
                  version=$(cat ./README.md | grep -oP 'v\d+\.\d+\.\d+')
                  echo "version=$version" >> $GITHUB_OUTPUT

            - name: Checkout To V8 Repo
              uses: actions/checkout@v4
              with:
                  repository: denoland/rusty_v8
                  ref: ${{ steps.get_version.outputs.version }}
                  fetch-depth: 10
                  submodules: recursive

            - name: Install Rust
              uses: dsherret/rust-toolchain-file@v1

            - name: Install Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11.x
                  architecture: x64

            - name: Test
              run: cargo test -vv --all-targets --locked ${{ env.CARGO_VARIANT_FLAG }}
                  --target ${{ env.TARGET }}
